import { useNavigate } from "react-router-dom";

function FacultyDashboard() {
  const navigate = useNavigate();
  const name = localStorage.getItem("name") || "Faculty";

  const handleLogout = () => {
    localStorage.clear();
    navigate("/login");
  };

  return (
    <div className="dashboard-container">
      <div className="dashboard-header">
        <div className="dashboard-title">
          <h1>Faculty Portal</h1>
          <p>Welcome back, Professor {name}!</p>
        </div>
        <button className="logout-btn" onClick={handleLogout}>
          Logout
        </button>
      </div>

      <div className="dashboard-grid">
        <div className="dashboard-card">
          <h3>⚡ Generate QR Session</h3>
          <p>Instantly generate attendance sessions and dynamically cycle secure QR verification codes for students.</p>
        </div>

        <div className="dashboard-card">
          <h3>📊 Attendance Analytics</h3>
          <p>Monitor real-time participation statistics, track class records, and export reports for administrative reviews.</p>
        </div>

        <div className="dashboard-card">
          <h3>👨‍🎓 Student Management</h3>
          <p>Review student records, approve attendance adjustment requests, and check performance scores.</p>
        </div>

        <div className="dashboard-card">
          <h3>💬 Grading & Feedback</h3>
          <p>Evaluate coding assessments and review mock interview statistics generated by the AI agent.</p>
        </div>
      </div>
    </div>
  );
}

export default FacultyDashboard;
